import { readFileSync, writeFileSync } from 'node:fs';
const tokens = JSON.parse(readFileSync(new URL('../src/styles/tokens.json', import.meta.url), 'utf8'));
const mapping = Object.fromEntries(Object.keys(tokens.light).filter(key => !key.startsWith('ef-') && key !== 'radius').map(key => [`color-${key}`, `var(--${key})`]));
Object.assign(mapping, tokens.theme, { 'radius-sm': 'calc(var(--radius) * 0.6)', 'radius-md': 'calc(var(--radius) * 0.8)', 'radius-lg': 'var(--radius)', 'radius-xl': 'calc(var(--radius) * 1.4)' });
const block = (selector, object) => `${selector} {\n${Object.entries(object).map(([key, value])=>`  --${key}: ${value};`).join('\n')}\n}`;
const css = `/* Generated by scripts/build-theme.mjs. Edit src/styles/tokens.json. */
@import "tailwindcss";
@import "tw-animate-css";
@import "@fontsource-variable/dm-sans";
@custom-variant dark (&:is(.dark *));

${block('@theme inline', mapping)}
${block(':root', tokens.light)}
${block('.dark', tokens.dark)}

@layer base {
  * { @apply border-border; }
  html { font-family: var(--font-sans); color-scheme: light; }
  html.dark { color-scheme: dark; }
  body { margin: 0; background: var(--background); color: var(--foreground); font-size: 1rem; line-height: 1.5; }
  button, a, input, select, textarea { -webkit-tap-highlight-color: transparent; }
}
`;
writeFileSync(new URL('../src/styles/theme.css', import.meta.url), css);
console.log('Built theme CSS from shared tokens.');
