import { readFileSync, writeFileSync } from 'node:fs';
export const readJson = path => JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'));
export const styles = {
  editorial: {tokens: readJson('../src/styles/tokens.json'), fonts: ['@fontsource-variable/dm-sans']},
  stone: {tokens: readJson('../src/styles/stone.tokens.json'), fonts: ['@fontsource-variable/geist','@fontsource-variable/geist-mono','@fontsource-variable/source-serif-4']}
};
const config = readJson('../system.config.json');
const selected = styles[config.defaultStyle ?? 'editorial'];
if (!selected) throw new Error(`Unknown defaultStyle: ${config.defaultStyle}`);
const {tokens, fonts} = selected;
const mapping = Object.fromEntries(Object.keys(tokens.light).filter(key => !key.startsWith('ef-') && key !== 'radius').map(key => [`color-${key}`, `var(--${key})`]));
Object.assign(mapping, tokens.theme, { 'radius-sm': 'calc(var(--radius) * 0.6)', 'radius-md': 'calc(var(--radius) * 0.8)', 'radius-lg': 'var(--radius)', 'radius-xl': 'calc(var(--radius) * 1.4)' });
const block = (selector, object) => `${selector} {\n${Object.entries(object).map(([key, value])=>`  --${key}: ${value};`).join('\n')}\n}`;
const css = `/* Generated by scripts/build-theme.mjs. Edit source tokens and system.config.json. */
@import "tailwindcss";
@import "tw-animate-css";
${fonts.map(font=>`@import "${font}";`).join('\n')}
@custom-variant dark (&:is(.dark *));
${block('@theme inline', mapping)}
${block(':root', tokens.light)}
${block('.dark', tokens.dark)}
@layer base {
  * { @apply border-border; }
  html { font-family: var(--font-sans); color-scheme: light; }
  html.dark { color-scheme: dark; }
  body { margin: 0; background: var(--background); color: var(--foreground); font-size: 1rem; line-height: 1.5; }
  button, a, input, select, textarea { -webkit-tap-highlight-color: transparent; }
}
`;
writeFileSync(new URL('../src/styles/theme.css', import.meta.url), css);
const preview = `/* Generated. Reference-app comparison only; products use theme.css. */\n` + [...new Set(Object.values(styles).flatMap(s=>s.fonts))].map(font=>`@import "${font}";`).join('\n') + '\n' + Object.entries(styles).map(([name,{tokens}])=>block(`:root[data-style="${name}"]`, tokens.light)+'\n'+block(`:root.dark[data-style="${name}"]`, tokens.dark)).join('\n');
writeFileSync(new URL('../src/styles/preview-themes.css', import.meta.url), preview);
console.log(`Built ${config.defaultStyle} default theme and both reference styles.`);
